# Generated by Django 4.2.11 on 2024-04-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productURL', models.CharField(max_length=500)),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.TextField()),
                ('productCategory', models.CharField(max_length=200)),
                ('productPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('productTotalQuantity', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
